"""add last_post_date in users

Revision ID: 16a42cb424ee
Revises: a30f1e337a92
Create Date: 2026-05-14 16:20:26.289142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a42cb424ee'
down_revision: Union[str, Sequence[str], None] = 'a30f1e337a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_post_date', sa.DateTime(), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'last_post_date')
    # ### end Alembic commands ###
