"""add indexes and fix problems

Revision ID: f9c55f171c84
Revises: 2a76f995f31e
Create Date: 2026-05-15 17:14:54.842683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c55f171c84'
down_revision: Union[str, Sequence[str], None] = '2a76f995f31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_status_id'), 'posts', ['status_id'], unique=False)
    op.create_index(op.f('ix_users_status_id'), 'users', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status_id'), table_name='users')
    op.drop_index(op.f('ix_posts_status_id'), table_name='posts')
    # ### end Alembic commands ###
